name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs when code is pushed to `main` branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest image tag
        id: get-tag
        run: |
          TAG=$(curl -s "https://hub.docker.com/v2/repositories/hassan120478/website/tags" | jq -r '.results[].name' | grep -Eo '[0-9]+' | sort -nr | head -n1)
          if [ -z "$TAG" ]; then TAG=0; fi
          NEW_TAG=$((TAG + 1))
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            hassan120478/website:web-${{ env.NEW_TAG }}
            hassan120478/website:latest
