name: build_and_push_to_manifest
env:
  IMAGE_REGISTRY_REPO: hassan120478/website
  APP-NAME: website
on:
  push:
    branches:
      - 'main'

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build Docker Image
        run: |
          docker build -f Dockerfile -t $IMAGE_REGISTRY_REPO:${GITHUB_SHA::8} .

      - name: Push Image to Docker Hub
        run: |
          docker push $IMAGE_REGISTRY_REPO:${GITHUB_SHA::8}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - name: Checkout Manifest Repository
        uses: actions/checkout@v2.4.2
        with:
          repository: Ahmedhassan120478/manifest
          token: ${{ secrets.GH_PAT}}
          path: manifest  # Clone into 'manifest' directory

      - name: Update Image in Helm Chart
        shell: bash
        run: |
          cd manifest/helm
          export commitnum=${GITHUB_SHA::8}
          echo "Updating image repository and tag..."
          yq e -i '.image.repository = "hassan120478/website"' values.yaml
          yq e -i '.image.tag = env(commitnum)' values.yaml
          echo "Updated values.yaml:"
          cat values.yaml

      - name: Push Updated Helm Manifest
        run: |
          cd manifest
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "${GITHUB_REPOSITORY}_${GITHUB_JOB}_${GITHUB_SHA::7}_Updated image repository and tag"
          git push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
